# Generated by Django 3.0.8 on 2020-07-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k12App', '0002_auto_20200726_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='k12App.Question'),
        ),
        migrations.AlterField(
            model_name='upvote',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='k12App.Answer'),
        ),
    ]
